### ISSUE TITLE
BUGS in code

### ISSUE THREAD

**Issue by smbilal1984** [wzsong17/recsys21_insert#1]
i find following error in code, could you help me.
`TypeError: ProgressBar.__init__() got an unexpected keyword argument 'prefix'`
`
TypeError                                 Traceback (most recent call last)
Input In [36], in <cell line: 458>()
    468 batch_sum = 0
    469 get_ipython().run_line_magic('pinfo', 'progressbar.ProgressBar')
--> 470 pbar = progressbar.ProgressBar(maxval=num_batch_train,prefix='{variables.batch} >> {variables.loss} ||',variables={'batch': '--', 'loss': '--'})
    471 while not args.eval:
    473     batch_users, cur_sess, cur_sess_len, hist_sess, frds_sess = dataset.get_next_train_batch()

TypeError: ProgressBar.__init__() got an unexpected keyword argument 'prefix'`

**Comment by wzsong17** [comment]
> 

Hi, this error stems from the wrong installed version of the progressbar package. I recommend removing all code about the progressbar. It is only used to display the progress of the training progress and is not a necessary part of the insert algorithm.

**Comment by smbilal1984** [comment]
Thank you for quick response. after removing code of progressbar, i am facing followung error.
`DGLError: DGLGraph.group_apply_edges is removed in 0.5.`

` output = model(batch_users, cur_sess, hist_sess, frds_sess, cur_sess_len)`
`Algorithm:` INSERT: [[all]]
Loading dataset from data/fm2_delicious.pkl
Dataset loaded in 3.0s
Dataset: delicious
#users 1643, #items 5005
Starting epoch 1 ...

---------------------------------------------------------------------------
DGLError                                  Traceback (most recent call last)
Input In [6], in <cell line: 457>()
    474 if c_batch_size == 0:
    475     break
--> 476 output = model(batch_users, cur_sess, hist_sess, frds_sess, cur_sess_len)
    477 loss = model.loss(output, cur_sess_len)
    478 optimizer.zero_grad()

File ~\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

Input In [6], in INSERT.forward(self, users, cur_sess, hist_sess, frds_sess, cur_sess_len)
    124 query = hs#self.avg_encoder(cur_sess, cur_sess_len)[0]
    125 hist_sess_graph, frd_sess_graph = self.build_graph(users, hist_sess, frds_sess)
--> 126 hu, hf = self.hist_emb(query, hist_sess_graph, frd_sess_graph)
    128 # TODO 去掉用户历史
    129 hu = torch.zeros_like(hs).to(device)

Input In [6], in INSERT.hist_emb(self, query, hist_sess, frd_sess)
    354 ## 2. calculating session similarity and filtering dissimilar links
    355 hist_sess.apply_nodes(self.sess_encoder, ntype='session')
--> 357 hist_sess.group_apply_edges('dst',self.sess_similarity, etype='sess2user')
    358 filter_hist_sess = hist_sess.filter_edges(lambda edges: edges.data['prev'], etype='sess2user')
    359 filtered_hist_sess = hist_sess.edge_subgraph({'sess2user':filter_hist_sess})

File ~\Anaconda3\envs\pytorch\lib\site-packages\dgl\heterograph.py:6122, in DGLHeteroGraph.group_apply_edges(self, group_by, func, edges, etype, inplace)
   6120 def group_apply_edges(self, group_by, func, edges=ALL, etype=None, inplace=False):
   6121     """**DEPRECATED**: The API is removed in 0.5."""
-> 6122     raise DGLError('DGLGraph.group_apply_edges is removed in 0.5.')

DGLError: DGLGraph.group_apply_edges is removed in 0.5.





`

**Comment by wzsong17** [comment]
> 

please try to install the dgl package version == 0.4.3post2 (cpu or gpu)

**Comment by wzsong17** [comment]
> 

please try to install the dgl package version == 0.4.3post2 (cpu or gpu)
